services:
  # Master
  node-master:
    build: 
      dockerfile: Dockerfile
      context: ./base-node/.
      args:
        - type=master
    image: mu-master:latest
    container_name: node-master
    environment:
      - WORKER_MODE=MASTER
    hostname: node-master
    ports:
      - "7077:7077" 
      - "11000:11000"
      - "8080:8080"

      # YARN UI
      - "8088:8088"

      # HDFS UI
      - "9870:9870"

      # Timeline service
      - "19888:19888"
      - "10020:10020"
      - "8188:8188"

      # Livy
      - "8998:8998"

      # Spark UI
      - "18080:18080"

    networks:
      - net

  # Slaves
  node-slave-1:
    build: 
      dockerfile: Dockerfile
      context: ./base-node/.
      args:
        - type=slave
    image: mu-slave:latest
    depends_on:
      - node-master
    tty: true
    environment:
      - WORKER_MODE=SLAVE
    ports:
      - "8042:8042"
      - "9861:9861"
      - "8864:9864"
    container_name: node-slave-1
    hostname: node-slave-1
    networks:
      - net

  
  node-slave-2:
    build: 
      dockerfile: Dockerfile
      context: ./base-node/.
      args:
        - type=slave
    image: mu-slave:latest
    tty: true
    depends_on:
      - node-master
    environment:
      - WORKER_MODE=SLAVE
    ports:
      - "8043:8043"
      - "9862:9862"
      - "7864:9864"

    container_name: node-slave-2
    hostname: node-slave-2
    networks:
      - net

  jupyterlab:
    build: 
      dockerfile: Dockerfile
      context: ./spark-magic/.
    container_name: jupyterlab
    environment:
      - UID=$UID
      - GID=$GID
    image: spark-magic:latest
    ports:
      - "8888:8888"
    networks:
      - net
    volumes:
      - "./notebooks:/home/lab:rw"

networks:
  net:
    name: munetwork
    driver: bridge