include:
  - networks.yml
  - storage.yml

services:
  # Master
  node-master:
    platform: linux/amd64
    build: 
      dockerfile: Dockerfile
      context: ../cluster/.
      args:
        - type=master
        - metastore_user=${METASTORE_USER}
        - metastore_pass=${METASTORE_PASS}
    container_name: node-master
    hostname: node-master
    depends_on:
      - metastore
      - minio
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "7077:7077" 
      - "11000:11000"
      - "8080:8080"
      - "8032:8032"

      # YARN UI
      - "8088:8088"

      # HDFS UI
      - "9870:9870"
      - "2181:2181"

      # Timeline service
      - "19888:19888"
      - "10020:10020"
      - "8188:8188"

      # Livy
      - "8998:8998"

      # Spark UI
      - "18080:18080"

      # Hive
      - "12000:12000"
      - "12001:12001"
      - "12002:12002"
      - "12003:12003"

    networks:
      - net

  # Slaves
  node-slave-1:
    platform: linux/amd64
    build: 
      dockerfile: Dockerfile
      context: ../cluster/.
      args:
        - type=slave
    depends_on:
      - node-master
    ports:
      - "8042:8042"
      - "9861:9861"
      - "8864:9864"
    container_name: node-slave-1
    hostname: node-slave-1
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - net

  
  node-slave-2:
    platform: linux/amd64
    build: 
      dockerfile: Dockerfile
      context: ../cluster/.
      args:
        - type=slave
    container_name: node-slave-2
    hostname: node-slave-2
    depends_on:
      - node-master
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8043:8043"
      - "9862:9862"
      - "7864:9864"
    networks:
      - net